# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:15
from __future__ import unicode_literals

from django.db import migrations
from craigslist.models import State
import us


def create_states(apps, schema_editor):
    for state in us.states.STATES:
        s = State(state=str(state))
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_states)
    ]
